### ISSUE TITLE
Simple contains search fails

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-plugin#2]
Searching for `rdfs:label` contains `Cell` fails in this [ontology](https://github.com/bdionne/protege-server/blob/metaproject-integration/samples/foo.owl). Interestingly property present and absent work ok.

**Comment by rsgoncalves** [comment]
I get the class `Cell` back as a result. Do you get no results at all?

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/lucene-search-plugin/commit/2cfd45410cb1d15efe1bf10c6e4ec3bdf7e03235

**Comment by bdionne** [comment]
yea I get no results, though ends with "ell" finds it

I'll try the patch

**Comment by bdionne** [comment]
still fails here

**Comment by johardi** [comment]
There is case sensitivity issue in the search string

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/lucene-search-plugin/commit/8658c6446aa97754e3a8bc1b99f4cb634ca2532c
