### ISSUE TITLE
SearchTabManager listener throws exception when loading ontology from server

### ISSUE THREAD

**Issue by rsgoncalves** [protegeproject/lucene-search-plugin#31]
Output:

Loaded ontology, now updating from server
Initializing index 
Unable to open the ontology owlapi:ontology88990897241320 
Exception thrown by listener: org.protege.editor.search.nci.SearchTabManager$2.  Detatching bad listener.

**Comment by johardi** [comment]
I couldn't reproduce the error. Can you try to remove any existing index directories from the preferences panel please and see if it fixes the issue.

**Comment by rsgoncalves** [comment]
That might have done it. I can't replicate anymore, so I'm closing this for now.
