### ISSUE TITLE
Query strings with hyphens in them produce 0 results

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-plugin#34]
![screen shot 2016-08-17 at 12 39 07 pm](https://cloud.githubusercontent.com/assets/31741/17744969/01156916-6478-11e6-8ad9-ef136617e8c2.png)

If you delete the hyphen:

![screen shot 2016-08-17 at 12 42 19 pm](https://cloud.githubusercontent.com/assets/31741/17744988/18718e8c-6478-11e6-94d1-82711b0124ea.png)

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/lucene-search-plugin/commit/67792922742f8524cd03606e88508ebc407c3d79
