### ISSUE TITLE
Indexer rebuilds complete index whenever rdfs:label is added to a class

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-plugin#36]
Steps to reproduce:
1. In the classes tab add a new child class to a class
2. select the new child and add an rdfs:label

Not sure if this is a search or protege issue, the call to [rebuild](https://github.com/protegeproject/lucene-search-plugin/blob/nci-lucene-search/src/main/java/org/protege/editor/search/nci/SearchTabManager.java#L136) occurs because an `ENTITY_RENDERING_CHANGED` is thrown by [`OWLEntityAnnotationValueRenderer`](https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/ui/renderer/OWLEntityAnnotationValueRenderer.java#L72) whenever an `rdfs:label` is involved. @matthewhorridge the comment in that code makes me suspect you didn't necessarily want to throw this event.

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/lucene-search-plugin/commit/a8c7c65da2c3e8ee9957689cc2d862907e135156
