### ISSUE TITLE
Need the ability to display classes being exported

### ISSUE THREAD

**Issue by bdionne** [protegeproject/lucene-search-plugin#38]
This is functionality  we had in the old system. The [ExportToCSVAction](https://github.com/NCIEVS/nci-protege/blob/master/deps-1.4.3/advancedQuery/src/edu/stanford/smi/protege/query/ui/NCIExportToCsvAction.java) could be subclassed to optionally display a list of classes.

The classes could then be deleted or added to. This is used by the report writer in edit tab.

![functionality](https://cloud.githubusercontent.com/assets/31741/17874750/a3b62f80-689b-11e6-9738-14fab46c3e54.png)

I neglected to add this to the requirements, though it is in the plan, my bad. Please assess how much effort it takes to add this.

**Comment by rsgoncalves** [comment]
Where do the classes come from? Are those a subset of the results list?

**Comment by bdionne** [comment]
no, they come from the report writer. The user might select some classes in the navigation pane or they may specify an input file with a list of codes to look them up. Either way they are passed as a list to the exporter much as the search results are. If you look at the old one, it was done with callbacks to retrieve the list and a boolean was passed to the exporter to determine whether or not to display it. 

To clarify, the third option, the one selected in the screenshot, doesn't use the lucene exporter, it does a recursive walk of the tree from the selected root.

![screen shot 2016-08-24 at 1 10 51 pm](https://cloud.githubusercontent.com/assets/31741/17940256/4d41cd5a-69fc-11e6-85c7-69f5de505684.png)

**Comment by rsgoncalves** [comment]
If I understand correctly then this breaks down to 2 things:
- ability to pass a set of classes to the `CsvExporter`
- `ExportDialogPanel` should display the given set of classes, and allow adding/removing classes

**Comment by bdionne** [comment]
exactly, and allowing `ExportDialogPanel` to not display the set of classes, so it can work as it does now in the search tab.

**Comment by rsgoncalves** [comment]
Ok, I'm working on this.
